spring:
  cloud:
    stream:
      bindings:
        pos-invoice-input-channel:
          destination: avro-pos-invoice-topic
      kafka:
        streams:
          binder:
            brokers: localhost:9092
            configuration:
              schema.registry.url: http://localhost:8081
              # processing.guarantee is set to at_least_once by default.
              # creating a single listener that will perform atomic operations
              processing.guarantee: exactly_once
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde